/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: 'class',
    theme: {
        extend: {
            fontFamily: {
                'poppins': ['Poppins', 'sans-serif'],
                'quicksand': ['Quicksand', 'sans-serif'],
                'raleway': ['Raleway', 'sans-serif'],
                'nunito': ['Nunito', 'sans-serif'],
            },
            colors: {
                primary: {
                    DEFAULT: '#FF6B6B',
                    dark: '#FF5252',
                    light: '#FF8080',
                },
                secondary: {
                    DEFAULT: '#4ECDC4',
                    dark: '#45B7AF',
                    light: '#66D3CC',
                },
                dark: {
                    bg: '#1a1a1a',
                    card: '#2d2d2d',
                    text: '#e5e5e5',
                },
            },
            backgroundColor: {
                'dark-bg': '#1a1a1a',
                'dark-card': '#2d2d2d',
                'primary-dark': '#FF5252',
                'primary-light': '#FF8080',
                'secondary-dark': '#45B7AF',
                'secondary-light': '#66D3CC',
            },
            textColor: {
                'dark-text': '#e5e5e5',
            },
        },
    },
    plugins: [require("daisyui")],
    daisyui: {
        themes: [
            {
                light: {
                    ...require("daisyui/src/theming/themes")["light"],
                    "primary": "#FF6B6B",
                    "primary-focus": "#FF5252",
                    "primary-content": "#ffffff",
                    "secondary": "#4ECDC4",
                    "secondary-focus": "#45B7AF",
                    "secondary-content": "#ffffff",
                    "accent": "#FFD93D",
                    "accent-focus": "#FFD000",
                    "accent-content": "#000000",
                    "neutral": "#3d4451",
                    "neutral-focus": "#2a2e37",
                    "neutral-content": "#ffffff",
                    "base-100": "#ffffff",
                    "base-200": "#f9fafb",
                    "base-300": "#f3f4f6",
                    "base-content": "#1f2937",
                },
                dark: {
                    ...require("daisyui/src/theming/themes")["dark"],
                    "primary": "#FF6B6B",
                    "primary-focus": "#FF5252",
                    "primary-content": "#ffffff",
                    "secondary": "#4ECDC4",
                    "secondary-focus": "#45B7AF",
                    "secondary-content": "#ffffff",
                    "accent": "#FFD93D",
                    "accent-focus": "#FFD000",
                    "accent-content": "#000000",
                    "neutral": "#2a2e37",
                    "neutral-focus": "#16181d",
                    "neutral-content": "#ffffff",
                    "base-100": "#1a1a1a",
                    "base-200": "#2d2d2d",
                    "base-300": "#404040",
                    "base-content": "#e5e5e5",
                },
            },
        ],
        darkTheme: "dark",
        base: true,
        styled: true,
        utils: true,
        prefix: "",
        logs: false,
        themeRoot: ":root",
    },
}
